### ISSUE TITLE
ตัวละคร Boss Red Eye Frog

### ISSUE THREAD

**Issue by SRTxz** [Akkarapo/G4#7]

**Comment by Akkarapo** [comment]
![Boss_2](https://github.com/Akkarapo/G4/assets/112610820/4f1135ec-dc96-4b42-bbbd-9c7ce4075be4)
![Boss_7](https://github.com/Akkarapo/G4/assets/112610820/83073518-be53-4ce6-81ce-394dc78000c9)
![Boss_1](https://github.com/Akkarapo/G4/assets/112610820/578de535-3a6e-4b89-ae38-0115a84c9880)
